#!/bin/bash
# script for Installer DVD OS X El Capitan  

hdiutil makehybrid -o "$HOME/Desktop/Mac OS X Install DVD.iso" "${3}/" -iso -hfs -joliet -eltorito-boot "${3}/usr/standalone/i386/cdboot" -no-emul-boot -hfs-volume-name "Mac OS X Install DVD" -joliet-volume-name "Mac OS X Install DVD"

# detach volumes
hdiutil detach -Force /Volumes/Mac-OSX-Install-DVD

# Remove the dmg
rm /tmp/Mac-OSX.sparseimage




exit