#!/bin/bash
# Mac OS X Install DVD Creator # Copyright (c) 2016, 2026 chris1111
# Vars
apptitle="Mac OS X Install DVD Creator"
version="1.6" 
# Set Icon directory and file 
export ICNS=$(dirname "${0}")
iconfile="$ICNS/AppIcon.icns"

# Confirmation Dialog
response=$(osascript -e 'tell app "System Events" to display dialog "Please read this before clicking OK\n\nNOTE: If you have already create 
Mac OS X Install DVD.iso on the desktop, it will automatically deleted by the program. ​So If you would like to create more disk images; put the images in a folder apart before continue." buttons {"Cancel", "OK"} default button 2 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'" ')
answer=$(echo $response | grep "OK")  

# Cancel is user does not select OK
if [ ! "$answer" ] ; then
  osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
  echo "QUITAPP"
  killall "MacOSX-Install-DVD"
fi

if [[ $(mount | awk '$3 == "/Volumes/Mac-OSX-Install-DVD" {print $3}') != "" ]]; then
 hdiutil detach -Force "/Volumes/Mac-OSX-Install-DVD"
fi

if [[ -d "/Volumes/Mac OS X Install DVD" ]]; then
 hdiutil detach -Force "/Volumes/Mac OS X Install DVD"
fi

if [ "/tmp/Mac-OSX.sparseimage" ]; then
	rm -rf "/Private/tmp/Mac-OSX.sparseimage"
fi

if [ "/$HOME/Desktop/Mac OS X Install DVD.iso" ]; then
	rm -rf "/$HOME/Desktop/Mac OS X Install DVD.iso"
fi

echo "**********************************************  "
echo "Starting Installer Mac OS X Install DVD!  "   
echo "**********************************************  "
Sleep 1
osascript <<EOD
# If Continue		set theAction to button returned of (display dialog "
Choose the location of your Install macOS.app" with icon 2 buttons {"Quit", "Install macOS"} default button {"Install macOS"})if theAction = "Quit" then	display dialog "Quitter Installer" with icon note buttons {"EXIT"} default button {"EXIT"}
        delay 1	do shell script "killall MacOSX-Install-DVD"	returnend ifif theAction = "Install macOS" then	--If Install macOS		set InstallOSX to choose file of type {"XLSX", "APPL"} default location (path to applications folder) with prompt "Choose your Install macOS.app"	set OSXInstaller to POSIX path of InstallOSX	delay 2	do shell script "hdiutil attach -noverify -nobrowse -mountpoint /Private/tmp/Installer-OS \"" & OSXInstaller & "Contents/SharedSupport/InstallESD.dmg\""end if
EOD



Sleep 1
echo "**********************************************  "
echo "Create sparseimage!  "   
echo "**********************************************  "
# create sparseimage
hdiutil create -size 8g -type SPARSE -fs HFS+J -volname Mac-OSX-Install-DVD -uid 0 -gid 80 -mode 1775 /Private/tmp/Mac-OSX
echo "  "
echo "**********************************************  "
echo "Mount Installer image!  "
echo "**********************************************  "
Sleep 1
osascript -e 'display notification "Installer Mac OS X Install DVD" with title "Starting"  sound name "default"'
# Mount the dmg image
hdiutil attach -nobrowse /Private/tmp/Mac-OSX.sparseimage
echo " "
echo "**********************************************  "
echo " "
echo "Installation  /Volumes/Mac-OSX-Install-DVD
Create /Desktop/Mac OS X Install DVD.iso 
Volume name /Mac OS X Install DVD
Wait, be patient! . . . "
echo " "
# run the pkg
osascript -e 'do shell script "installer -allowUntrusted -verboseR -pkg ./Installer.pkg -target /Volumes/Mac-OSX-Install-DVD" with administrator privileges'
echo "  "

osascript <<EOD
  tell application "MacOSX-Install-DVD"
      activate
  end tell
EOD

echo "**********************************************  "
echo "Unmount Installer image!  "
echo "**********************************************  "
Sleep 1
hdiutil detach -Force /Private/tmp/Installer-OS
Sleep 1
echo "**********************************************  "
echo "Mount Mac OS X Install DVD!  "   
echo "**********************************************  "
Open ~/Desktop/"Mac OS X Install DVD.iso"
echo "**********************************************  "
echo "Mac OS X Install DVD Done !  "
echo "**********************************************  "
